[package]
id = "cool-tts"
version = "0.1.0"
name = "Cool TTS Service"
favicon_ico = "💬"

[dependencies]
"nix:uv" = "*"

[build]
exec = "uv sync"
execDir = "."
env = {}
args = []

[intents."ui.TextToSpeech"]
invocation = "pipe"
execDir = "."
exec = "uv run python -m make-wavs --intent-server"
env = {}
args = []