[package]
id = "org.unix.cool-player"
name = "Cool Media Player"

[intents.media.PlayStream]
handler = "cards/player.html"
accepts_mime = [
  "video/x-raw-yuv",
  "video/mp4",
  "audio/pcm"
]

media.transports = ["file", "socket"]