#include <stdio.h>
#include <stdlib.h>
#include "quickjs.h"

static JSRuntime *rt = NULL;
static JSContext *ctx = NULL;
static JSValue global_obj;
static JSValue jslib_exports;

// Shared library constructor: Runs automatically when host calls dlopen("libjslib.so")
__attribute__((constructor))
static void init_embedded_quickjs(void) {
    rt = JS_NewRuntime();
    ctx = JS_NewContext(rt);
    global_obj = JS_GetGlobalObject(ctx);

    // Embedded bytecodes of jslib.js generated by qjsc / quickjs-bundle
    const char *jslib_code = "module.exports = { add: (a, b) => a + b };";
    
    // Evaluate JS source / bytecode and extract module.exports
    JSValue eval_res = JS_Eval(ctx, jslib_code, strlen(jslib_code), "<embedded>", JS_EVAL_TYPE_GLOBAL);
    JS_FreeValue(ctx, eval_res);

    jslib_exports = JS_GetPropertyStr(ctx, global_obj, "exports");
}

// =========================================================================
// EXPORTED C SYMBOL (dlsym target)
// =========================================================================
// Host calls: dlsym(handle, "jslib_add")
__attribute__((visibility("default")))
int32_t jslib_add(int32_t a, int32_t b) {
    // 1. Fetch function from module.exports
    JSValue fn = JS_GetPropertyStr(ctx, jslib_exports, "add");
    
    // 2. Marshal C arguments to QuickJS JSValues
    JSValue args[2];
    args[0] = JS_NewInt32(ctx, a);
    args[1] = JS_NewInt32(ctx, b);

    // 3. Enter QuickJS Context & Execute
    JSValue result = JS_Call(ctx, fn, JS_UNDEFINED, 2, args);

    // 4. Unbox return value back to C primitive
    int32_t c_res = 0;
    JS_ToInt32(ctx, &c_res, result);

    // 5. Cleanup temporary JSValues (Garbage Collection management)
    JS_FreeValue(ctx, fn);
    JS_FreeValue(ctx, args[0]);
    JS_FreeValue(ctx, args[1]);
    JS_FreeValue(ctx, result);

    return c_res;
}

// Shared library destructor: Runs on dlclose()
__attribute__((destructor))
static void cleanup_embedded_quickjs(void) {
    JS_FreeValue(ctx, jslib_exports);
    JS_FreeValue(ctx, global_obj);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
}