# demonstrates tts
[app]
id = "org.xintent.cool-ebook"
version = "0.1.0"
name = "Cool Ebooks"
description = "EPub Demonstrator"

[app.main]
type = "html"
card = "main"

[[cards]]
id = "main"
path = "index.html"
title = "Cool Ebooks"

[intents."fs.Open"]
invocation = "html"
card = "main"